import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.DASHBOARD.TEXT",
    iconType: "feather",
    icon: "home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "",
    title: "MENUITEMS.ADMIN.TEXT",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  // {
  //   path: "admin/parameter",
  //   title: "MENUITEMS.PARAMETER.TEXT",
  //   iconType: "material",
  //   icon: "opacity",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [
  //     {
  //       path: "admin/parameter/cleaning-category",
  //       title: "MENUITEMS.PARAMETER.LIST.CLEANING-CATEGORY",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //     {
  //       path: "admin/parameter/cleaning-methods",
  //       title: "MENUITEMS.PARAMETER.LIST.CLEANING-METHODS",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //   ]
  // },
  {
    path: "admin/cleaning-management",
    title: "MENUITEMS.TARIFF.TEXT",
    iconType: "material",
    icon: "trending_up",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "admin/tariff/tariff-cleaning",
        title: "MENUITEMS.TARIFF.LIST.TARIFF-CLEANING",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/tariff/tariff-depot",
        title: "MENUITEMS.TARIFF.LIST.TARIFF-DEPOT",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/tariff/tariff-labour",
        title: "MENUITEMS.TARIFF.LIST.TARIFF-LABOUR",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/tariff/tariff-repair",
        title: "MENUITEMS.TARIFF.LIST.TARIFF-REPAIR",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/tariff/tariff-buffer",
        title: "MENUITEMS.TARIFF.LIST.TARIFF-BUFFER",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/tariff/tariff-residue",
        title: "MENUITEMS.TARIFF.LIST.TARIFF-RESIDUE",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/tariff/tariff-steam",
        title: "MENUITEMS.TARIFF.LIST.TARIFF-STEAM",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ]
  },
  {
    path: "admin/cleaning-management",
    title: "MENUITEMS.PACKAGE.TEXT",
    iconType: "material",
    icon: "more",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "admin/package/package-cleaning",
        title: "MENUITEMS.PACKAGE.LIST.PACKAGE-CLEANING",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/package/package-depot",
        title: "MENUITEMS.PACKAGE.LIST.PACKAGE-DEPOT",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/package/package-labour",
        title: "MENUITEMS.PACKAGE.LIST.PACKAGE-LABOUR",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/package/package-repair",
        title: "MENUITEMS.PACKAGE.LIST.PACKAGE-REPAIR",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    
      {
        path: "admin/package/package-buffer",
        title: "MENUITEMS.PACKAGE.LIST.PACKAGE-BUFFER",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/package/package-residue",
        title: "MENUITEMS.PACKAGE.LIST.PACKAGE-RESIDUE",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/package/package-steam",
        title: "MENUITEMS.PACKAGE.LIST.PACKAGE-STEAMING",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/package/exclusive-steam",
        title: "MENUITEMS.PACKAGE.LIST.EXCLUSIVE-STEAMING",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ]
  },
  {
    path: "admin/cleaning-management",
    title: "MENUITEMS.CLEANING-MANAGEMENT.TEXT",
    iconType: "material",
    icon: "donut_small",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "admin/parameter/cleaning-category",
        title: "MENUITEMS.CLEANING-MANAGEMENT.LIST.CLEAN-CATEGORY",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/parameter/cleaning-methods",
        title: "MENUITEMS.CLEANING-MANAGEMENT.LIST.CLEAN-METHODS",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/cleaning-steps",
        title: "MENUITEMS.CLEANING-MANAGEMENT.LIST.CLEAN-STEPS",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
        visible: false
      },
      {
        path: "admin/cleaning-procedures",
        title: "MENUITEMS.CLEANING-MANAGEMENT.LIST.CLEAN-PROCEDURES",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
        visible: false
      },
      {
        path: "admin/cleaning-groups",
        title: "MENUITEMS.CLEANING-MANAGEMENT.LIST.CLEAN-GROUPS",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
        visible: false
      }
    ].filter(item => item.visible !== false),
  },
  {
    path: "admin/master",
    title: "MENUITEMS.MASTER.TEXT",
    iconType: "material",
    icon: "business_center",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "admin/master/estimate-template",
        title: "MENUITEMS.MASTER.LIST.ESTIMATE-TEMPLATE",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/master/customer",
        title: "MENUITEMS.MASTER.LIST.CUSTOMER",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: []
      },
      {
        path: "admin/master/billing-branch",
        title: "MENUITEMS.MASTER.LIST.BILLING-BRANCH",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: []
      },
      // {
      //   path: "admin/master/estimate-template/new",
      //   title: "MENUITEMS.MASTER.LIST.ASSIGN-ESTIMATE-TEMPLATE",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   submenu: [],
      // },
      {
        path: "admin/cleaning-steps",
        title: "MENUITEMS.CLEANING-MANAGEMENT.LIST.CLEAN-STEPS",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
        visible: false
      },
      {
        path: "admin/cleaning-procedures",
        title: "MENUITEMS.CLEANING-MANAGEMENT.LIST.CLEAN-PROCEDURES",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
        visible: false
      },
      {
        path: "admin/cleaning-groups",
        title: "MENUITEMS.CLEANING-MANAGEMENT.LIST.CLEAN-GROUPS",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
        visible: false
      }
    ].filter(item => item.visible !== false),
  },
  {
    path: "admin/inventory",
    title: "MENUITEMS.INVENTORY.TEXT",
    iconType: "material",
    icon: "compare_arrows",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "admin/inventory/storing-order",
        title: "MENUITEMS.INVENTORY.LIST.STORING-ORDER",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/inventory/in-gate",
        title: "MENUITEMS.INVENTORY.LIST.IN-GATE",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/inventory/in-gate-survey",
        title: "MENUITEMS.INVENTORY.LIST.IN-GATE-SURVEY",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/inventory/tank-movement",
        title: "MENUITEMS.INVENTORY.LIST.TANK-MOVEMENT",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/inventory/booking",
        title: "MENUITEMS.INVENTORY.LIST.BOOKING",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      // {
      //   path: "admin/inventory/booking-new",
      //   title: "MENUITEMS.INVENTORY.LIST.BOOKING-NEW",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   submenu: [],
      // },
      {
        path: "admin/inventory/scheduling",
        title: "MENUITEMS.INVENTORY.LIST.SCHEDULING",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      // {
      //   path: "admin/inventory/scheduling-new",
      //   title: "MENUITEMS.INVENTORY.LIST.SCHEDULING-NEW",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   submenu: [],
      // },
      {
        path: "admin/inventory/release-order",
        title: "MENUITEMS.INVENTORY.LIST.RELEASE-ORDER",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/inventory/out-gate",
        title: "MENUITEMS.INVENTORY.LIST.OUT-GATE",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ]
  },
  {
    path: "admin/repair",
    title: "MENUITEMS.REPAIR.TEXT",
    iconType: "material",
    icon: "build",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "admin/repair/estimate",
        title: "MENUITEMS.REPAIR.LIST.ESTIMATE",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/repair/approval",
        title: "MENUITEMS.REPAIR.LIST.APPROVAL",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/repair/job-order",
        title: "MENUITEMS.REPAIR.LIST.JOB-ORDER",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      }
    ]
  },
  {
    path: "admin/cleaning-management",
    title: "MENUITEMS.CLEANING.TEXT",
    iconType: "material",
    icon: "opacity",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "admin/cleaning/approval",
        title: "MENUITEMS.CLEANING.LIST.APPROVAL",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/cleaning/job-order",
        title: "MENUITEMS.CLEANING.LIST.JOB-ORDER",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      }
    ]
  },
  {
    path: "admin/cleaning-management",
    title: "MENUITEMS.RESIDUE-DISPOSAL.TEXT",
    iconType: "material",
    icon: "delete",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "admin/residue-disposal/estimate-approval",
        title: "MENUITEMS.RESIDUE-DISPOSAL.LIST.RESIDUE-DISPOSAL-ESTIMATE-APPROVAL",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/residue-disposal/estimate",
        title: "MENUITEMS.RESIDUE-DISPOSAL.LIST.RESIDUE-DISPOSAL-ESTIMATE",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
        visible: false
      },
      {
        path: "admin/residue-disposal/approval",
        title: "MENUITEMS.RESIDUE-DISPOSAL.LIST.RESIDUE-DISPOSAL-APPROVAL",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
        visible: false
      },
      {
        path: "admin/residue-disposal/job-order",
        title: "MENUITEMS.RESIDUE-DISPOSAL.LIST.JOB-ORDER",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      }
    ].filter(item => item.visible !== false),
  },
  {
    path: "admin/steam",
    title: "MENUITEMS.STEAM.TEXT",
    iconType: "material",
    icon: "whatshot",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "admin/steam/estimate-approval",
        title: "MENUITEMS.STEAM.LIST.STEAM-ESTIMATE-APPROVAL",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: []
      },
      {
        path: "admin/steam/estimate",
        title: "MENUITEMS.STEAM.LIST.STEAM-ESTIMATE",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
        visible: false
      },
      {
        path: "admin/steam/approval",
        title: "MENUITEMS.STEAM.LIST.STEAM-APPROVAL",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
        visible: false
      },
      {
        path: "admin/steam/job-order",
        title: "MENUITEMS.STEAM.LIST.JOB-ORDER",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      }
    ].filter(item => item.visible !== false),
  },
  {
    path: "admin/management",
    title: "MENUITEMS.MANAGEMENT.TEXT",
    iconType: "material",
    icon: "business_center",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "admin/management/user",
        title: "MENUITEMS.MANAGEMENT.LIST.USER",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/management/group",
        title: "MENUITEMS.MANAGEMENT.LIST.GROUP",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: []
      },
      {
        path: "admin/cleaning-groups",
        title: "MENUITEMS.CLEANING-MANAGEMENT.LIST.CLEAN-GROUPS",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
        visible: false
      }
    ].filter(item => item.visible !== false),
  },
  {
    path: "admin/survey",
    title: "MENUITEMS.SURVEY.TEXT",
    iconType: "material",
    icon: "event_note",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "admin/survey/periodic-test",
        title: "MENUITEMS.SURVEY.LIST.PERIODIC-TEST-SURVEY",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "admin/survey/others",
        title: "MENUITEMS.SURVEY.LIST.OTHERS-SURVEY",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      }
    ]
  },
  // {
  //   path: "advance-table",
  //   title: "MENUITEMS.ADVANCE-TABLE.TEXT",
  //   iconType: "feather",
  //   icon: "trello",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },

  // Common Modules
  // {
  //   path: "",
  //   title: "Authentication",
  //   iconType: "feather",
  //   icon: "user-check",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [
  //     {
  //       path: "/authentication/signin",
  //       title: "Sign In",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //     {
  //       path: "/authentication/signup",
  //       title: "Sign Up",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //     {
  //       path: "/authentication/forgot-password",
  //       title: "Forgot Password",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //     {
  //       path: "/authentication/locked",
  //       title: "Locked",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //     {
  //       path: "/authentication/page404",
  //       title: "404 - Not Found",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //     {
  //       path: "/authentication/page500",
  //       title: "500 - Server Error",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Extra Pages",
  //   iconType: "feather",
  //   icon: "anchor",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [
  //     {
  //       path: "/extra-pages/blank",
  //       title: "Blank Page",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Multi level Menu",
  //   iconType: "feather",
  //   icon: "chevrons-down",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [
  //     {
  //       path: "/multilevel/first1",
  //       title: "First",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //     {
  //       path: "/",
  //       title: "Second",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-sub-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [
  //         {
  //           path: "/multilevel/secondlevel/second1",
  //           title: "Second 1",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-menu2",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           submenu: [],
  //         },
  //         {
  //           path: "/",
  //           title: "Second 2",
  //           iconType: "",
  //           icon: "",
  //           class: "ml-sub-menu2",
  //           groupTitle: false,
  //           badge: "",
  //           badgeClass: "",
  //           submenu: [
  //             {
  //               path: "/multilevel/thirdlevel/third1",
  //               title: "third 1",
  //               iconType: "",
  //               icon: "",
  //               class: "ml-menu3",
  //               groupTitle: false,
  //               badge: "",
  //               badgeClass: "",
  //               submenu: [],
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //     {
  //       path: "/multilevel/first3",
  //       title: "Third",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //   ],
  // },
];
